### ISSUE TITLE
In "non-english" mode actor returns wrong currency

### ISSUE THREAD

**Issue by OlehVeselov92** [tugkan/aliexpress-scraper#22]
There is an issue with currency only when you choose not-English language (maybe because each language has different domain, fr.aliexpress.com for French, for example)

Reason of different currency is in Proxy.
If I run actor locally with` "useApifyProxy": false`, it always returns "EUR".
If you use proxy, mostly, it returns "USD", sometimes absolutely another currency.
I logged headers in response. There is` set-cookie` array. Among them, there are: `region=` and `c_tp=` (this cookie we use in our request to set desired currency).
And due to `region=` (IP location), there is different `c_tp=` value in response. And looks like each time Aliexpress replaces our `c_tp` cookie.

In "Postman" app with cookie, we use, request always returns correct currency.

@pocesar  suggested to set persistCookiesPerSession: false , but it didn't help.

**Comment by pocesar** [comment]
I think the correct way would to require residentials and set the country, for precision. if the user doesn't care about the currency precision, he can use other proxies just to get the basic (loose) information, and convert the currency by himself if needed
